import { Header } from "@/components";
import React from "react";
import './global.css';

export const metadata = {
  title: 'Next JS new style ',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}: { children: React.ReactNode }) {

  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  )
}
